### ISSUE TITLE
Update `.gitignore` to omit `.swiftpm` folder.

### ISSUE THREAD

**Issue by ShikiSuen** [laosb/CropImage#5]
This folder is temporarily generated and not needed to be memorized in git.

<img width="127" alt="image" src="https://github.com/user-attachments/assets/294f30ca-db5b-4a1b-9981-bbd1fe8a8af4" />

**Comment by laosb** [comment]
I don't think it's right to `gitignore` the whole `.swiftpm` folder though; see: https://stackoverflow.com/questions/65754188/should-i-add-swiftpm-to-gitignore

I don't think there's a consensus yet on which things in `.swiftpm` should be ignored, so let's keep it there before we can narrow it down.
